name: Build bootc ISO
on:
  push:
    tags:
      - '*'
jobs:
  build:
    name: Build bootc image

    runs-on: ubuntu-24.04
    env:
      IMAGE_NAME: homelab-turbo-one-amd64
      REGISTRY: ghcr.io/ferrory
   
    steps:
      - name: Clone the repository
        uses: actions/checkout@v4

      # workaround for https://github.com/redhat-actions/podman-login/issues/42 since the docker config from the host doesn't come up to the container
      - name: Workaround open podman-login action issue
        env:
          auth: "{ \"auths\": {} }"
        run: |
          mkdir -p $HOME/.docker
          echo $auth > $HOME/.docker/config.json
      - name: Log in to the GitHub Container registry
        uses: redhat-actions/podman-login@v1
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.CR_PAT }}

      - name: Build ISO
        id: build-iso
        uses: osbuild/bootc-image-builder-action@019bb59c5100ecec4e78c9e94e18a840110f7a0b # v0.0.2
        with:
          config-file: ./config.toml
          image: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:latest
          types: |
            iso
          rootfs: xfs

      - name: Upload iso to release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.REPO_TOKEN }}
          file: ${{ steps.build-iso.outputs.output-directory }}/bootiso/install.iso
          asset_name: homelab-turbo-one-amd64-iso
          tag: ${{ github.ref }}
          overwrite: true
          body: "homelab turbo-one server iso file."

